<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB3yg578\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB3yg578/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB3yg578.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB3yg578\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerB3yg578\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'B3yg578',
    'container.build_id' => 'a3b5005f',
    'container.build_time' => 1645530547,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB3yg578');
