<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'materiel_index' => [[], ['_controller' => 'App\\Controller\\MaterielController::index'], [], [['text', '/materiel/']], [], []],
    'materiel_new' => [[], ['_controller' => 'App\\Controller\\MaterielController::new'], [], [['text', '/materiel/new']], [], []],
    'materiel_show' => [['id'], ['_controller' => 'App\\Controller\\MaterielController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/materiel']], [], []],
    'materiel_edit' => [['id'], ['_controller' => 'App\\Controller\\MaterielController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/materiel']], [], []],
    'materiel_delete' => [['id'], ['_controller' => 'App\\Controller\\MaterielController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/materiel']], [], []],
    'reclamation_index' => [[], ['_controller' => 'App\\Controller\\ReclamationController::index'], [], [['text', '/reclamation/']], [], []],
    'reclamation_new' => [[], ['_controller' => 'App\\Controller\\ReclamationController::new'], [], [['text', '/reclamation/new']], [], []],
    'reclamation_show' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/reclamation']], [], []],
    'reclamation_edit' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/reclamation']], [], []],
    'reclamation_delete' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/reclamation/reclamation_delete']], [], []],
];
